### ISSUE TITLE
Missing `local` arg in sourced command documentation

### ISSUE THREAD

**Issue by driosalido** [src-d/sourced-ce#108]
The Initialize sourced community edition doc is missing the `local` argument in the [local repositories section](https://github.com/src-d/sourced-ce/blob/master/docs/quickstart/3-init-sourced.md#from-local-repositories)
```
$ sourced init </path/to/repositories>
```

should be 

```
$ sourced init local </path/to/repositories>
```

**Comment by dpordomingo** [comment]
Thanks for reporting, should be fixed by https://github.com/src-d/sourced-ce/pull/110
