### ISSUE TITLE
Query results on Jupyter notebooks

### ISSUE THREAD

**Issue by marnovo** [src-d/sourced-ce#112]
What is the best way right now to get query results in a jupyter notebook?

Example use case that was done with the source{d} Engine:
https://github.com/src-d/engine-analyses/blob/master/k8s_analysis.ipynb
(see `In [3]:` and `In [43]:` cells from the notebook)

**Comment by smacker** [comment]
gitbase is exposed on a standard mysql port. You can still connect to it in absolutely the same way as before.

**Comment by marnovo** [comment]
Excellent. @dpordomingo makes sense to document this in [advanced usage](https://github.com/src-d/sourced-ce/tree/master/docs#advanced-usage)?

**Comment by dpordomingo** [comment]
About gitbase being exposed to be used for other tools from the outside is something already documented by https://docs.sourced.tech/community-edition/learn-more/architecture#docker-networking.

But yes, we could provide some examples of use cases where anyone could use source{d} components from the outside, for example connecting to gitbase with a Jupyter Notebook, or connecting to Babelfish from any other app.

Question. Would it be better if done in our docs? or in our Forum?

**Comment by marnovo** [comment]
Docs! Then we can create a FAQ question in the forum and link to it.

**Comment by marnovo** [comment]
P.s.: worked perfectly just changing the connection parameters to the ones from `docker-compose.yml` 👍

**Comment by dpordomingo** [comment]
This should be done by https://github.com/src-d/sourced-ce/pull/120
