### ISSUE TITLE
Use 127.0.0.1 consistently

### ISSUE THREAD

**Issue by dpordomingo** [src-d/sourced-ce#116]
_Originally posted by @EgorBu in https://github.com/src-d/sourced-ui/issues/172#issuecomment-506390457_

A bit of feedback from empathy session
https://github.com/src-d/empathy-sessions/issues/41

We should not mix `localhost` & `127.0.0.1`
https://github.com/src-d/sourced-ce#quick-start contains `localhost` when UI contains `127.0.0.1` - it requires to login one more time

**Comment by carlosms** [comment]
I've changed the title and moved it from -ui to -ce because we open `127.0.0.1` from the CLI, and the welcome dashboard links are also `127.0.0.1`. I think the logical thing to do is replace `localhost` in the docs.
