### ISSUE TITLE
Pass SQL queries straight to `sql` command

### ISSUE THREAD

**Issue by marnovo** [src-d/sourced-ce#117]
Is it possible to pass SQL queries directly to the `sourced sql` command [like it was in the source{d} Engine](https://github.com/src-d/engine#query-command-line-interface-cli)?
```SQL
# Run query via CLI
srcd sql "SHOW tables;"
```

**Comment by smacker** [comment]
currently, it's not supported but is easy to add

**Comment by dpordomingo** [comment]
This should be done by https://github.com/src-d/sourced-ce/pull/122
