### ISSUE TITLE
Broken link in the email

### ISSUE THREAD

**Issue by ckorikov** [src-d/sourced-ce#133]
I got an email with a link to download **sourced-ce** but it redirects me to the page with "not found". The link is below.

[https://github.com/src-d/sourced-ce/releases/download/v0.13.0/engine_v0.13.0_darwin_amd64.tar.gz](https://github.com/src-d/sourced-ce/releases/download/v0.13.0/engine_v0.13.0_darwin_amd64.tar.gz)

**Comment by marnovo** [comment]
Hi @ckorikov, thanks for reporting it! Did you get the email yesterday/today? Thank you.

**Comment by ckorikov** [comment]
Hi @marnovo! I got the email yesterday.

**Comment by vcoisne** [comment]
@ckorikov You should have received another email with [correction] in the subject with the right link. Please let me know if you have received it or need me to resend it.

**Comment by ckorikov** [comment]
@vcoisne yes, I received a new email with the correct link.

**Comment by carlosms** [comment]
Thanks for reporting it.
