### ISSUE TITLE
Notify the users of new releases

### ISSUE THREAD

**Issue by carlosms** [src-d/sourced-ce#14]
When this was discussed the `docker-compose.yml` and the `sourced` binary releases were assumed to be independent.
But now that both are in the same repository and will be released together, I think the reasonable functionality is to assume an update means "update `sourced`" exclusively.

Any `sourced` command should check the `latest` release tag from github, and show a warning to the user with a link to the release.

**Comment by dpordomingo** [comment]
should it show the warning every time the user runs a `sourced` command and there is a new release? or should it be shown from time to time (once per hour, day...)?

**Comment by carlosms** [comment]
I think for now let's just show it on every command, it will be simpler.
My only concern with that is if it will slow down the usage if we do an http request constantly.

Maybe we could create an http cache in `/tmp`, this way we will not slow down every single command. And the the cache expiration, I'd choose something like 24h.
