### ISSUE TITLE
source{d} CE v0.14.0-rc.1 doesn't seem to create ~/.sourced folder

### ISSUE THREAD

**Issue by gomesfernanda** [src-d/sourced-ce#160]
When upgrading to version [v0.14.0-rc.1](https://github.com/src-d/sourced-ce/releases/tag/v0.14.0-rc.1) of source{d} CE, I followed

1) the guideline on Releases section

### Upgrading

For internal releases we don't support upgrading. If you have a previous sourced-ce version installed, clean up all your data before downloading this release. This will delete everything, including the UI data for dashboards, charts, users, etc:

```bash
sourced prune --all
rm -rf ~/.sourced
```

2) then the instruction on [source{d} CE Quickstart](https://docs.sourced.tech/community-edition/quickstart/2-install-sourced)

### On Linux or macOS

Extract sourced binary from the release you downloaded, and move it into your bin folder to make it executable from any directory:

```bash
$ tar -xvf path/to/sourced-ce_REPLACE-VERSION_REPLACE-OS_amd64.tar.gz
$ sudo mv path/to/sourced-ce_REPLACE-OS_amd64/sourced /usr/local/bin/
```

However, when I tried using source{d} CE, I got an error.

```bash
$ sourced init local ~/engine-srcd/repos/bblfsh
> /Users/fernandagomes/.sourced does not exist
> Cannot perform this action, source{d} needs to be initialized first with the 'init' sub command
```

Noticing that the folder didn't exist, I created it

`$ mkdir /Users/fernandagomes/.sourced`

and everything worked.

I believe there's a bug on this version, where it doesn't create this folder (~/.sourced) when the user initializes the tool.

**Comment by dpordomingo** [comment]
Ouch!, I didn't notice about that when reviewing https://github.com/src-d/sourced-ce/pull/153/files#diff-4a88fdaf8ab4c4ad4b300c67fd60be64R32
Many other commands failed, e.g. `sourced compose download`.

**Comment by dpordomingo** [comment]
Thanks for reporting @gomesfernanda 
The fix is already released by https://github.com/src-d/sourced-ce/releases/tag/v0.14.0-rc.2
