### ISSUE TITLE
Consider removing `completion` command on Windows

### ISSUE THREAD

**Issue by se7entyse7en** [src-d/sourced-ce#169]
While investigating #168. 

The `completion` command is specific to bash. Given that we've been testing `sourced-ce` with `powershell` as we used to do for [engine](https://github.com/src-d/engine-deprecated), it makes sense to remove it for Windows.

**Comment by dpordomingo** [comment]
I think we should move this to https://github.com/src-d/go-cli
wdyt @smola ?

**Comment by carlosms** [comment]
Reopening because https://github.com/src-d/go-cli/pull/20 does not fix this one until we update the version in go.mod

**Comment by dpordomingo** [comment]
Since we're not using `cli.New`, but `cli.NewNoDefaults`, and then we're manually adding the `cli.CompletionCommand`, I think that the fix provided by src-d/go-cli#20 won't solve our problem.

https://github.com/src-d/go-cli/pull/21 should solve our problem.
