### ISSUE TITLE
`workdirs` command assumes that path is b64 encoded

### ISSUE THREAD

**Issue by se7entyse7en** [src-d/sourced-ce#173]
The `workdirs` command assumes that the path is base64 encoded, but this is true only for non-local initialization. This is a screenshot of the output of `sourced workdirs` with one initialized as `local` and another as `org`:

<img width="848" alt="Screenshot 2019-07-30 at 21 25 47" src="https://user-images.githubusercontent.com/5599208/62158815-9f998d80-b310-11e9-93f5-f3d6f816c7ff.png">

**Comment by se7entyse7en** [comment]
The problem is that we assume that here:
```
	// workdirs for remote orgs encoded into base64
	decoded, err := base64.StdEncoding.DecodeString(p)
	if err == nil {
		return string(decoded), nil
	}
```
an error is raised when sourced-ce is initialized with `local`. But actually, some valid paths could be base64 decoded correctly.

**Comment by carlosms** [comment]
While we are at it, we should change the encoding from `base64.StdEncoding` to `base64.URLEncoding`, which is safe to use as file name.

**Comment by carlosms** [comment]
After discussing it in slack we will go with this structure:
```
~/.sourced/workdirs/
├─ __active__
├─ local
│  ├── base64(path1)
│  ├── base64(path2)
│  └── ...
└─ orgs
   ├── base64(orgs1)
   ├── base64(orgs2)
   └── ...
```

This groups deployments initialized with `init local` or `init orgs`, and this can be handy in the future. At the same time, having base64 for both local and orgs makes the code easier. And it removes problems when you initialize both with `/some/path` and `/some/path/subdir`.

Using `URLEncoding`.
