### ISSUE TITLE
[Idea] Provide a `workdirs jump` sub command

### ISSUE THREAD

**Issue by se7entyse7en** [src-d/sourced-ce#174]
Sometimes a user may want to do some advanced management using `docker-compose` directly. We could provide a `sourced workdirs jump` subcommand that `cd`s into the current active workdir.

**Comment by dpordomingo** [comment]
I think it's not a good idea to expose internals that way.

That advanced user could just do:
```shell
$ cd ~/.sourced/workdirs/__active__
```
or even configure their own alias:
```shell
$ alias sourcedActive='cd ~/.sourced/workdirs/__active__'
```
and then just run
```shell
$ sourcedActive
```
instead of `sourced workdirs jump`

**Comment by se7entyse7en** [comment]
Okay, gonna close this then 👍.
