### ISSUE TITLE
Add GOPROXY to travis

### ISSUE THREAD

**Issue by carlosms** [src-d/sourced-ce#198]
Let's add goproxy to travis, it should speed up the build times.
See related issue: https://github.com/src-d/regression-core/pull/17

**Comment by smacker** [comment]
<img width="633" alt="Screenshot 2019-08-07 at 12 56 09" src="https://user-images.githubusercontent.com/406916/62617716-c0667200-b912-11e9-95fd-baf1e68a89ee.png">

**Comment by se7entyse7en** [comment]
This is blocked by https://github.com/src-d/ci/pull/105, unless we want to add it in the `.travis.yml` file in the meantime.

**Comment by smacker** [comment]
go1.13 was released 3 days ago. It uses proxy by default. We need only to update `.travis.yml` to the new version.

**Comment by dpordomingo** [comment]
This should be done by https://github.com/src-d/sourced-ce/pull/242
