### ISSUE TITLE
Forbidden error while accessing docker compose file when initializing local Git repositories using source{d}

### ISSUE THREAD

**Issue by srinath-chandra** [src-d/sourced-ce#206]
When I try to initialize the local git repositories using source{d}, I get forbidden error for accessing the docker compose file.
$>sourced init local repos/
Get https://raw.githubusercontent.com/src-d/sourced-ce/v0.14.0-rc.2/docker-compose.yml: Forbidden
$>sourced status
error while getting docker-compose container: error downloading https://github.com/docker/compose/releases/download/1.24.0/run.sh: Get https://github.com/docker/compose/releases/download/1.24.0/run.sh: Forbidden

Please help me to mitigate this.!

**Comment by carlosms** [comment]
Hi,

You might want to use v0.14.0 instead of v0.14.0-rc.2. Although it should not affect the downloads in any way.

Can you share your OS details? Thanks.

**Comment by srinath-chandra** [comment]
Hi Carlos, Thank you for the quick response.!

I have used v0.14.0 now, but still the same error. My OS is SUSE 12 Pack 3.

$>sourced init local repos/
Get https://raw.githubusercontent.com/src-d/sourced-ce/v0.14.0/docker-compose.yml: Forbidden
$>sourced logs
error while getting docker-compose container: error downloading https://github.com/docker/compose/releases/download/1.24.0/run.sh: Get https://github.com/docker/compose/releases/download/1.24.0/run.sh: Forbidden

**Comment by carlosms** [comment]
Does a regular `wget https://raw.githubusercontent.com/src-d/sourced-ce/v0.14.0/docker-compose.yml` work for you?

As a workaround, to fix your local installation while we figure out what can be happening, you can download [the file](https://raw.githubusercontent.com/src-d/sourced-ce/v0.14.0/docker-compose.yml) and place it in `~/.sourced/compose-files/v0.14.0/docker-compose.yml`.
Then run `sourced compose set v0.14.0`.

**Comment by srinath-chandra** [comment]
I actually do not have access to external/public sites, figuring out the proxies if any! I will check with Network team and will get back if still any issue.

**Comment by carlosms** [comment]
Closing since it's not an issue in sourced-ce.
