### ISSUE TITLE
Add gitbase-spark-connector to the compose file

### ISSUE THREAD

**Issue by carlosms** [src-d/sourced-ce#207]
After the latest roadmap discussions about EE and CE, `sourced-ce` will deploy only one `docker-compose.yml`, there will not be 2 versions.

CE will be similar to what we have today, but using `gitbase-spark-connector`.
Since there is still some work needed in other projects, we will start working with PRs against a new branch, `gsc`.

Until we have a proper public release of gitbase-spark-connector, we will have to use the private `-enterprise` image.

Open question: what will we do with the `sourced sql` command.

**Comment by se7entyse7en** [comment]
> Open question: what will we do with the `sourced sql` command.

Related to this: https://github.com/src-d/sourced-ce/issues/170.

**Comment by se7entyse7en** [comment]
See [here](https://github.com/src-d/sourced-ui/issues/235#issuecomment-537488079).
