### ISSUE TITLE
Docker exits with 1 when "sourced init local <repo>"

### ISSUE THREAD

**Issue by cmbahadir** [src-d/sourced-ce#210]
Hi There,

I have faced with an error when i wanted to initiliaze a local repo with command;

**sourced init local <repo_path>**

When i check the "docker-compose logs" below ERROR is seen;

**WARNING: The GITBASE_SIVA variable is not set. Defaulting to a blank string.
WARNING: The GITBASE_VOLUME_SOURCE variable is not set. Defaulting to a blank string.
WARNING: The GITBASE_VOLUME_TYPE variable is not set. Defaulting to a blank string.
ERROR: Invalid interpolation format for "environment" option in service "ghsync": "${GITHUB_ORGANIZATIONS:-}"**

And i also ran the integration tests with "make test-integration-no-build" and below tests were failed;
Local:

**--- FAIL: TestInitLocalTestSuite/TestChangeWorkdir (0.51s)
        require.go:794: 
            	Error Trace:	init_local_test.go:62
            	Error:      	Received unexpected error:
            	            	exit status 1
            	Test:       	TestInitLocalTestSuite/TestChangeWorkdir
            	Messages:   	docker-compose working directory set to /tmp/TestInitLocalTestSuite_TestChangeWorkdir948094188/sourced/workdirs/local/L3RtcC9UZXN0SW5pdExvY2FsVGVzdFN1aXRlX1Rlc3RDaGFuZ2VXb3JrZGlyOTQ4MDk0MTg4L3dvcmtkaXJfYQ==
            	            	Define and run multi-container applications with Docker.**

Orgs:

 **FAIL: TestInitOrgsTestSuite (4.05s)
    --- FAIL: TestInitOrgsTestSuite/TestOneOrg (4.05s)
        require.go:794: 
            	Error Trace:	init_orgs_test.go:100
            	Error:      	Received unexpected error:
            	            	exit status 1
            	Test:       	TestInitOrgsTestSuite/TestOneOrg
            	Messages:   	docker-compose working directory set to /tmp/TestInitOrgsTestSuite_TestOneOrg097538814/sourced/workdirs/orgs/Z29sYW5nLW1pZ3JhdGU=
            	            	Define and run multi-container applications with Docker.**

Also when i try to build with copied docker-compose.yml i get the following error for GITHUB_TOKEN even it is set as environment variable;

**/tmp/TestInitLocalTestSuite_TestChangeWorkdir335919161/sourced/workdirs/local/L3RtcC9UZXN0SW5pdExvY2FsVGVzdFN1aXRlX1Rlc3RDaGFuZ2VXb3JrZGlyMzM1OTE5MTYxL3dvcmtkaXJfYQ==$ docker-compose build
ERROR: Invalid interpolation format for "environment" option in service "ghsync": "${GITHUB_TOKEN:-}"**

Error message is not clear, as long as you run docker-compose logs and i couldn't find any info about why/how to set the "GITHUB_ORGANIZATIONS" environment variable for a local repo. 

Seems like there is a problem setting environment variables in docker-compose ymls.

OS : Linux Mint 
docker-compose version: 1.17.1
sourced-ce : latest master

Thanks in advance.

**Comment by se7entyse7en** [comment]
This `invalid interpolation` error has been encountered also in https://github.com/src-d/sourced-ce/issues/167 with your very same version of `docker-compose`. Could you try updating it?

**Comment by se7entyse7en** [comment]
By looking at [`docker-compose` CHANGELOG](https://github.com/docker/compose/blob/master/CHANGELOG.md), this interpolation feature has been added since [`v1.9.0`](https://github.com/docker/compose/blob/master/CHANGELOG.md#190-2016-11-16):

> Added support for shell-style inline defaults in variable interpolation. The supported forms are `${FOO-default}` (fall back if FOO is unset) and `${FOO:-default}` (fall back if FOO is unset or empty).

but a bug has been fixed in [`v1.18.0`](https://github.com/docker/compose/blob/master/CHANGELOG.md#1180-2017-12-15):

> Fixed a bug where the valid `${VAR:-}` syntax would cause Compose to error out

**Comment by smacker** [comment]
@se7entyse7en thanks for the investigation. We can mention minimum docker-compose version in readme or update docker-compose.yml by using `{FOO-default}` syntax if it doesn't error in older versions. (I would prefer the latter)

**Comment by se7entyse7en** [comment]
It makes sense to use `{FOO-default}` in our case.

**Comment by cmbahadir** [comment]
@se7entyse7en @smacker Thanks for the response.

I tried {FOO-default} with both versions 1.17.1 and 1.22.0 and it worked.

IMHO that would be nice to check the version of the docker-compose in the host if this is going to be fixed by editting the yml?

Also, should i close the issue? Seems like it is logical to keep it open until there is a PR.

**Comment by se7entyse7en** [comment]
> I tried with {FOO-default} with both versions 1.17.1 and 1.22.0 and it worked.

Thanks @cmbahadir for testing it!

Yup, I think that we could open a PR with the change that we discussed.
