### ISSUE TITLE
sourced init without the org parameter (or making it optional)

### ISSUE THREAD

**Issue by rpau** [src-d/sourced-ce#235]
Related with: https://github.com/src-d/sourced-ce/issues/61

Using the GH token is enough to discover the user orgs/repos of a user. In GHE, I have seen in big companies (e.g. > 1000 developers) to have an org per team to find easily the repos and administrate permissions in an isolated way. 

So, as a user/developer/manager, when I run it for first time, it was weird to me to filter an specific org.

**Comment by smola** [comment]
Note that users may be members of many organizations but could be interested only in some of them. In my case, I'm member of 10 organizations but use source{d} with only 2 of them. I see some possible behaviors here:

* If no explicit org is given, import all of them.
* If no explicit org is given, and the user only has access to one org, import that org. If there is more than one org, fail and ask the user to add organizations explicitly.
* None of the above, add an `--all` (or similar) option to fetch all organizations based on membership data.
* Status quo.

Note that a token can also be used to import organizations that you are not member of. I have no idea how common would that be for end users, it definitely is common for us while experimenting, but we can just be explicit with organizations in that case.

**Comment by smacker** [comment]
I really like how it's done in bb server. It figures what can be fetched with your token and asks what you want:
<img width="623" alt="Screenshot 2019-08-27 at 13 04 01" src="https://user-images.githubusercontent.com/406916/64610108-cd252c80-d3ce-11e9-8c45-bd45cc9270b5.png">

In "owner" on the top I have other orgs too.

**Comment by rpau** [comment]
+1 with @smacker 

Like BB, using the token you can ask for the orgs where the user belongs to, and then, he should be able select from the UI which orgs/repos wants to analyse.

Also, Wwen you setup travis, you enable the orgs and repos to process.

**Comment by se7entyse7en** [comment]
@rpau I think we can close this in favor of [this](https://github.com/src-d/applications-backlog/issues/5).
