### ISSUE TITLE
Update to go-1.13

### ISSUE THREAD

**Issue by carlosms** [src-d/sourced-ce#238]
Go 1.13 is out, according to [our conventions](https://github.com/src-d/guide/blob/master/engineering/conventions/go.md#supported-go-versions) we should update.

**Comment by dpordomingo** [comment]
Do we want to use `go1.13` error wrapping instead of current `go-error`?
Should we confirm it company-wide?

**Comment by carlosms** [comment]
I would say yes, but it's something we can do later. Maybe we can open a new issue to src-d/guide to discuss it (as the convention is documented here https://github.com/src-d/guide/blob/master/engineering/conventions/go.md#error-handling)

**Comment by dpordomingo** [comment]
> I would say yes, but it's something we can do later. Maybe we can open a new issue to src-d/guide to discuss it (as the convention is documented here https://github.com/src-d/guide/blob/master/engineering/conventions/go.md#error-handling)

Good idea. Issue opened here https://github.com/src-d/guide/issues/383
