### ISSUE TITLE
`docker-compose.override.yml` file breaks the `compose` sub cmd

### ISSUE THREAD

**Issue by carlosms** [src-d/sourced-ce#252]
The override file must match the compose file format version of the main `docker-compose.yml` file.
While the main `docker-compose.yml` file is managed by `sourced compose`, the contents of the `docker-compose.override.yml` file are hardcoded into the `sourced` bin.

See for example the upgrading instructions here https://github.com/src-d/sourced-ce/pull/251/files

Why is the `docker-compose.override.yml` file needed at all in `sourced`? Can we find a way to manage this cleanly from the preparation scripts of `sourced-ui` instead?

**Comment by smacker** [comment]
I think we can remove everything about override from srcd-ce.
If a developer needs an override for a new workdir he/she can just execute `make set-override` in srcd-ui again. What is your opinion @se7entyse7en ?

**Comment by se7entyse7en** [comment]
I agree. I also actually never used `docker-compose.override.yml` and also even did't remember why we added it. Moreover, it's an internal thing that has an impact to the end-user as it makes updating less friendly (even if it's just a matter of an additional instruction).

**Comment by se7entyse7en** [comment]
@dpordomingo wdyt?

**Comment by dpordomingo** [comment]
In the PR https://github.com/src-d/sourced-ce/pull/158 which added it, I initially implemented the safety net to ensure that it wouldn't collide with any user state. It was suggested to make it static, and I did so.
:man_shrugging: 

Yes, we can also delete it and take another approach. There are always different alternatives, and considering our current state, maybe that's the fastest one.

**Comment by se7entyse7en** [comment]
Okay, let's remove it then.

**Comment by dpordomingo** [comment]
This caused https://github.com/src-d/sourced-ui/issues/318
