### ISSUE TITLE
Identify and show errors for old unsupported version of docker/docker-compose

### ISSUE THREAD

**Issue by smacker** [src-d/sourced-ce#253]
On linux `docker-compose` gets installed separately from `docker` and can be very old.
In such case `sourced-ce` doesn't work and produces either strange or no errors at all.

We need to identify such old versions and ask a user to update the dependencies.

**Comment by dpordomingo** [comment]
Do you know what is the lower supported version?

We should also document it [docs/quickstart/1-install-requirements.md#docker-compose](https://github.com/src-d/sourced-ce/blob/master/docs/quickstart/1-install-requirements.md#docker-compose)
