### ISSUE TITLE
Rename .srcd to .sourced

### ISSUE THREAD

**Issue by carlosms** [src-d/sourced-ce#36]
The dir `~/.srcd` comes from the one we used in Engine, but since the command is `sourced` I think it makes sense to rename it to `~/.sourced` too.

**Comment by dpordomingo** [comment]
I assume it is not needed any migration process, so the user will be in charge of pruning old services and start the new ones.
So it should be said in the release notes.

(an alternative, that I don't know if it will work (I'll double check it when updating `CHANGELOG.md`), would be to rename `~/.srcd` to be `~/.sourced`. If it works, it would be easier and more convenient, wouldn't it?)

**Comment by carlosms** [comment]
We don't have any stable releases yet, there is no migration needed. Manual or automatic.
