### ISSUE TITLE
Add a section in the readme for timeouts

### ISSUE THREAD

**Issue by carlosms** [src-d/sourced-ce#56]
There are some limitations with how superset handles long-running sql queries, and it affects the dashboard charts.

This should be documented in a new section of the readme, explaining the kind of errors that can be expected, and how to refresh data when they are found.

**Comment by dpordomingo** [comment]
I'm not sure about understanding this...
Is this related to the problem that freezes the UI in some circumstances (like the first visit)? If I understood that case, gitbase is over-demanded while all the queries from the charts from the dashboard are being called at once, so the user should wait and force reload the broken charts when the UI is ready again.

Is that correct?

**Comment by dpordomingo** [comment]
so... is this related to https://github.com/src-d/sourced-ui/issues/121?

**Comment by carlosms** [comment]
Yes, they are related. And yes, I think your description matches the current situation. The users can get this message, or just have the UI freeze.

"Query timeout - visualization queries are set to timeout at 300 seconds. Perhaps your data has grown, your database is under unusual load, or you are simply querying a data source that is too large to be processed within the timeout range. If that is the case, we recommend that you summarize your data further."
