### ISSUE TITLE
Add github token and orgs validation

### ISSUE THREAD

**Issue by smacker** [src-d/sourced-ce#59]
Parent: #47

We need to validate incorrect input early because we can't catch errors when containers are started already.

**Comment by carlosms** [comment]
If we need to, maybe this could be done in ghsync with a new sub command. And from sourced-ce do a `compose exec`

**Comment by smacker** [comment]
It makes sense to implement the logic for validation in `ghsync`. And then:
1. compose stop
2. compose run --rm --no-deps ghsync validate
3. compose up

We need `--no-deps` to avoid starting postgres for validation.
