### ISSUE TITLE
Rename init command

### ISSUE THREAD

**Issue by smacker** [src-d/sourced-ce#60]
Parent #47 

Currently we have `init` and `orgs init`.
Most probably we should have `local init` and `orgs init`.
But better to confirm with @marnovo before making the change to avoid renaming again to something else later.

**Comment by marnovo** [comment]
Context on the actions we're talking about:

1. Initialize sourced-ce using a local repository as dataset (repositories)
2. Initialize sourced-ce using github organization(s) as dataset (repositories + issues/PRs/etc)
3. Update/refresh the dataset of local repos (restart gitbase to discover new repositories and changes in them)
4. Update/refresh (fetch again) the dataset of github repos/metadata
5. Possibly more actions in the future that could apply only to local, to github, or to both.

So far `init` serves as both setting sourced-ce (and ee) up initially and to change datasets you're working with.

Context from [R6 release coordination doc](https://docs.google.com/a/sourced.tech/document/d/1YcK11_qHTN_cH8ES_GQaVv_s1gVNQtMZNJnd6hjImJw/edit?disco=AAAADF0s_3A) on this topic:

> **Marcelo Novaes de Oliveira**
> 2:05 AM Jun 14
> 
> Wouldn't it make more sense as
> `sourced init local`
> `sourced init orgs`
> from a semantic & hierarchical perspective?

> **Carlos Martín**
> 11:19 AM Jun 14
> Yes for these 2 commands in isolation. But I'm thinking we may have new commands that apply only to `local` or to `orgs`.
> 
> For example, a sub command to re-trigger the metadata and repos download will fail for local repos.
> Should this be named `sourced reinit`, or `sourced orgs reinit`?

> **Marcelo Novaes de Oliveira**
> 4:01 PM Jun 14
> But then these could also be like:
> `sourced reinit local`
> `sourced reinit orgs`
> 
> One does the routine for only the local data, the other for the org-imported data.
> 
> Or even just
> `sourced reinit`
> and it defaults to whatever is initiated already. I.e., if I ran `sourced init local`, the `reinit` would run for local.
> 
> P.s.: what do you think about there instead of reinit
> `sourced refresh`
> `sourced init refresh`
> 
> P.p.s: `local and orgs` can even be flags (w/ parameters when necessary) if this makes sense.

> **Carlos Martín**
> 4:26 PM Jun 14
> I don't like much the idea of flags, because then the documentation gets mixed. In this case the use case is quite different, and it gets super verbose to explain "this applies for this option but not for this, and you can mix this option with this one but not with this other one..."
> 
> reinit was just an example, it can be refresh or whatever other better name.
> 
> The point I was trying to make is that the command for "refresh github metadata" does not exist for local repositories. So if I do
> 
> sourced init local /path/to/repos
> sourced refresh-github-metadata-and-repos
> 
> And the second command fails, it can be confusing why. But if the structure is like this:
> 
> sourced local init /path/to/repos
> sourced orgs refresh-github-metadata-and-repos
> 
> It's more clear that I'm mixing 2 things
> 
> 
> Anyway the commands can be re arranged easily, we can just ignore this and pick up the conversation again when all the functionality is in place. It will be more obvious where to go

> **Marcelo Novaes de Oliveira**
> 11:05 AM Today
> Ahhh, I see your point!
> 
> On the other hand, if we have `orgs init` and `local init`, it's not very clear if you can really have both working at the same time, or what is the "active" dataset I'm working with?
> 
> In this case
> `sourced refresh orgs` does its thing
> but
> `sourced refresh` tells the user the subcommands
> `sourced refresh local` tells the user local repos don't need refresh
> 
> TBH I think we'll only nail this with iteration and user testing. It might be even that people see it more logical something else like `sourced dataset` or so. let's move this discussion to the actual issue on the repo:
> https://github.com/src-d/sourced-ce/issues/60
>

**Comment by marnovo** [comment]
@smacker can you confirm what does the init command does on the background when:

1. you run it for the first time: set up the whole thing + get containers etc + load dataset?
2. you run it afterwards: just load dataset?

Asking this because maybe part of the confusion to users is because we couple two different (semantically) steps into a single command.

(On a high level, no need to go too deep into details)

**Comment by smacker** [comment]
1. you run it for the first time: download images, starts containers, configures superset database (with user, datasources, imports default charts), runs gitcollector and ghsync in orgs mode.
2. stops old containers, recreates containers if changed (for example if you downloaded new `docker-compose.yml`), restarts containers with the same volumes as before (so all the state is preserved). So if nothing in containers configuration changed everything would continue work exactly the same as before re-init.

**Comment by smacker** [comment]
oh. just to be clean. both of the steps happen for each workdir. Workdirs (path to repos or list of orgs) are absolutely independent of each other.

**Comment by eiso** [comment]
I think refresh might make sense for now but it won't matter very quickly because we'll soon need to be doing this in the back end anyways out of the box for sourced to be useful. And at that point refresh will be automatic and a background job.

**Comment by marnovo** [comment]
@eiso one important thing is that periodic refreshes will be explicitly opted-in for the user (and can be forced at any time, of course).
Since CE doesn't support proper versioning for datasets, you don't want your data (& charts & findings) to change without you knowing it, or even while you work.
Plus, I can assure you that CE is very useful already out of the box, even without automatic refreshes—that's how it's has been so far. It will become even more useful, yes. ;)

**Comment by smacker** [comment]
I also want to mention that `sourced refresh` (which doesn't exist right now) makes sense for both orgs and local repositories.

- In case of orgs it can download changes from remote and update metadata
- For local mode restart gitbase to discover new repositories and changes in them

**Comment by marnovo** [comment]
For the sake of our sanity and peace of mind, let's keep it the way it is for now and review it with some more user data and testing.

**Comment by carlosms** [comment]
But right now is a very confusing combination:
- `sourced init`
- `sourced orgs init`

I'd prefer to pick one of:
**A**
- `sourced orgs init`
- `sourced local init`

**B**
- `sourced init orgs`
- `sourced init local`

**Comment by marnovo** [comment]
@carlosms @smacker alright, after going over our current CLI commands, a bunch of common CLI tools and reading about best practices let's adopt your Option B as the baseline, as it follows the <program> <action> <subject> <subject-details-parameters> logic which is closer to natural language and follows better our other patterns.

- `sourced init local <path>`
- `sourced init orgs <orgs>`
- `sourced refresh local <path>`
- `sourced refresh orgs <orgs>`
