### ISSUE TITLE
Workdir names inconsistency on fs

### ISSUE THREAD

**Issue by smacker** [src-d/sourced-ce#99]
For `local` mode we keep the original path from the root as a path to the workdir.
For `org` mode the path is base64 from orgs names.

Originally it was proposed to move all local workdirs in `local` subdirectory and orgs in `orgs`.
Though we have concerns about it and it was also proposed to use base64 for consistency and to simplify the logic inside cli.

There is no final decision yet, we need to discuss it.

**Comment by se7entyse7en** [comment]
Shall we close this as dup of #173?

**Comment by smacker** [comment]
the solution might be the same but the issues are different. The fix may close both.
